### Login como admin
POST http://localhost:5189/api/auth/login?username=admin&password=admin
Content-Type: application/json

{}

### Login como user
POST http://localhost:5189/api/auth/login?username=user&password=user
Content-Type: application/json

{}

### Acessar endpoint apenas para Admin
GET http://localhost:5189/api/secure/admin
Authorization: Bearer {{token}}

### Acessar endpoint acessavel por qualquer usuario autenticado
GET http://localhost:5189/api/secure/user
Authorization: Bearer {{token}}







### Login como user
### Acessar endpoint acessavel por qualquer usuario autenticado

# @name login
POST http://localhost:5189/api/auth/login?username=user&password=user
Content-Type: application/json

###

GET http://localhost:5189/api/secure/user
Authorization: Bearer {{login.response.body.$.token}}

###
